//Pattern  Challenge  - letter S
//

Integer n = 5;
for(Integer row = 1; row <=n; row++){
    String pattern = '';
        	
    if(row == 1 || row == 3 || row == n){
        for(Integer i = 0; i<=4; i++){
        pattern = pattern + '*//'; 
    }
    }
        else if(row == 2){
            (pattern = '*//');
                }
    else if(row == 4){
        (pattern = '            ' + '*//');
    }
    
    System.debug(pattern);
        
    }
    System.debug(pattern);
        
    }

            
        
